# Generated by Django 4.2.21 on 2025-06-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('FOOD', 'Food'), ('TRAVEL', 'Travel'), ('ACADEMICS', 'Academics'), ('RENT', 'Rent'), ('GROCERIES', 'Groceries'), ('OTHER', 'Other')], max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
